logging:
  level:
    root: info
    com.ebs.weather_spider: error
  file:
    name: log/app.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} === [%thread] === %-5level === %logger{50} === - %msg%n'
  logback:
    rollingpolicy:
      max-file-size: 100MB