insert into alert_level (name)
values ('红色'),
       ('橙色'),
       ('黄色'),
       ('蓝色');

insert into weather_city (code, url, name)
values ('57083', '/publish/forecast/AHA/zhengzhou.html', '郑州'),
       ('53898', '/publish/forecast/AHA/anyang.html', '安阳'),
       ('53990', '/publish/forecast/AHA/hebi.html', '鹤壁'),
       ('53978', '/publish/forecast/AHA/jiyuan.html', '济源'),
       ('53982', '/publish/forecast/AHA/jiaozuo.html', '焦作'),
       ('57091', '/publish/forecast/AHA/kaifeng.html', '开封'),
       ('57073', '/publish/forecast/AHA/luoyang.html', '洛阳'),
       ('57178', '/publish/forecast/AHA/nanyang.html', '南阳'),
       ('57171', '/publish/forecast/AHA/pingdingshan.html', '平顶山'),
       ('57051', '/publish/forecast/AHA/sanmenxia.html', '三门峡'),
       ('58005', '/publish/forecast/AHA/shangqiu.html', '商丘'),
       ('53986', '/publish/forecast/AHA/xinxiang.html', '新乡'),
       ('57297', '/publish/forecast/AHA/xinyang.html', '信阳'),
       ('57089', '/publish/forecast/AHA/xuchang.html', '许昌'),
       ('57195', '/publish/forecast/AHA/zhoukou.html', '周口'),
       ('57290', '/publish/forecast/AHA/zhumadian.html', '驻马店'),
       ('58207', '/publish/forecast/AHA/huangchuan.html', '潢川'),
       ('57186', '/publish/forecast/AHA/luohe.html', '漯河'),
       ('54900', '/publish/forecast/AHA/puyang.html', '濮阳'),
       ('57181', '/publish/forecast/AHA/baofeng.html', '宝丰'),
       ('53979', '/publish/forecast/AHA/boai.html', '博爱'),
       ('57087', '/publish/forecast/AHA/changge.html', '长葛'),
       ('53998', '/publish/forecast/AHA/changyuan.html', '长垣'),
       ('58100', '/publish/forecast/AHA/dancheng.html', '郸城'),
       ('57082', '/publish/forecast/AHA/dengfeng.html', '登封'),
       ('57274', '/publish/forecast/AHA/dengzhou.html', '邓州'),
       ('54903', '/publish/forecast/AHA/fanxian.html', '范县'),
       ('57179', '/publish/forecast/AHA/fangcheng.html', '方城'),
       ('53983', '/publish/forecast/AHA/fengqiu.html', '封丘'),
       ('57098', '/publish/forecast/AHA/fugou.html', '扶沟'),
       ('57080', '/publish/forecast/AHA/gongyi.html', '巩义'),
       ('58208', '/publish/forecast/AHA/gushi.html', '固始'),
       ('57299', '/publish/forecast/AHA/guangshan.html', '光山'),
       ('53995', '/publish/forecast/AHA/huaxian.html', '滑县'),
       ('58205', '/publish/forecast/AHA/huaibin.html', '淮滨'),
       ('57192', '/publish/forecast/AHA/huaiyang.html', '淮阳'),
       ('53985', '/publish/forecast/AHA/huixian.html', '辉县'),
       ('53988', '/publish/forecast/AHA/huojia.html', '获嘉'),
       ('53992', '/publish/forecast/AHA/junxian.html', '浚县'),
       ('57093', '/publish/forecast/AHA/lankao.html', '兰考'),
       ('53889', '/publish/forecast/AHA/linzhou.html', '林州'),
       ('57183', '/publish/forecast/AHA/linying.html', '临颍'),
       ('57056', '/publish/forecast/AHA/lingbao.html', '灵宝'),
       ('57067', '/publish/forecast/AHA/lushi.html', '卢氏'),
       ('57173', '/publish/forecast/AHA/lushan.html', '鲁山'),
       ('58101', '/publish/forecast/AHA/luyi.html', '鹿邑'),
       ('57298', '/publish/forecast/AHA/luoshan.html', '罗山'),
       ('57066', '/publish/forecast/AHA/luoning.html', '洛宁'),
       ('57071', '/publish/forecast/AHA/mengjin.html', '孟津'),
       ('57072', '/publish/forecast/AHA/mengzhou.html', '孟州'),
       ('57281', '/publish/forecast/AHA/biyang.html', '泌阳'),
       ('58004', '/publish/forecast/AHA/minquan.html', '民权'),
       ('54901', '/publish/forecast/AHA/nanle.html', '南乐'),
       ('57176', '/publish/forecast/AHA/nanzhao.html', '南召'),
       ('53993', '/publish/forecast/AHA/neihuang.html', '内黄'),
       ('57169', '/publish/forecast/AHA/neixiang.html', '内乡'),
       ('58008', '/publish/forecast/AHA/ningling.html', '宁陵'),
       ('57292', '/publish/forecast/AHA/pingyu.html', '平舆'),
       ('53972', '/publish/forecast/AHA/qinyang.html', '沁阳'),
       ('54902', '/publish/forecast/AHA/qingfeng.html', '清丰'),
       ('57294', '/publish/forecast/AHA/queshan.html', '确山'),
       ('57197', '/publish/forecast/AHA/runan.html', '汝南'),
       ('57078', '/publish/forecast/AHA/ruyang.html', '汝阳'),
       ('57075', '/publish/forecast/AHA/ruzhou.html', '汝州'),
       ('58301', '/publish/forecast/AHA/shangcheng.html', '商城'),
       ('57198', '/publish/forecast/AHA/shangshui.html', '商水'),
       ('57194', '/publish/forecast/AHA/shangcai.html', '上蔡'),
       ('57187', '/publish/forecast/AHA/sheqi.html', '社旗'),
       ('58104', '/publish/forecast/AHA/shenqiu.html', '沈丘'),
       ('57189', '/publish/forecast/AHA/suiping.html', '遂平'),
       ('54817', '/publish/forecast/AHA/taiqian.html', '台前'),
       ('57099', '/publish/forecast/AHA/taikang.html', '太康'),
       ('53991', '/publish/forecast/AHA/tangyin.html', '汤阴'),
       ('57273', '/publish/forecast/AHA/tanghe.html', '唐河'),
       ('57191', '/publish/forecast/AHA/tongxu.html', '通许'),
       ('57285', '/publish/forecast/AHA/tongbai.html', '桐柏'),
       ('57094', '/publish/forecast/AHA/weishi.html', '尉氏'),
       ('53994', '/publish/forecast/AHA/weihui.html', '卫辉'),
       ('57079', '/publish/forecast/AHA/wenxian.html', '温县'),
       ('53987', '/publish/forecast/AHA/wuzhi.html', '武陟'),
       ('57177', '/publish/forecast/AHA/wugang.html', '舞钢'),
       ('57185', '/publish/forecast/AHA/wuyang.html', '舞阳'),
       ('57193', '/publish/forecast/AHA/xihua.html', '西华'),
       ('57188', '/publish/forecast/AHA/xiping.html', '西平'),
       ('57156', '/publish/forecast/AHA/xixia.html', '西峡'),
       ('57296', '/publish/forecast/AHA/xixian.html', '息县'),
       ('58017', '/publish/forecast/AHA/xiayi.html', '夏邑'),
       ('57182', '/publish/forecast/AHA/xiangcheng.html', '襄城'),
       ('57196', '/publish/forecast/AHA/xiang-cheng.html', '项城'),
       ('57070', '/publish/forecast/AHA/xinan.html', '新安'),
       ('57293', '/publish/forecast/AHA/xincai.html', '新蔡'),
       ('57085', '/publish/forecast/AHA/xinmi.html', '新密'),
       ('57396', '/publish/forecast/AHA/xinxian.html', '新县'),
       ('57271', '/publish/forecast/AHA/xinye.html', '新野'),
       ('57086', '/publish/forecast/AHA/xinzheng.html', '新郑'),
       ('53984', '/publish/forecast/AHA/xiuwu.html', '修武'),
       ('53997', '/publish/forecast/AHA/yanjin.html', '延津'),
       ('57184', '/publish/forecast/AHA/yexian.html', '叶县'),
       ('57074', '/publish/forecast/AHA/yichuan.html', '伊川'),
       ('57065', '/publish/forecast/AHA/yiyang.html', '宜阳'),
       ('58111', '/publish/forecast/AHA/yongcheng.html', '永城'),
       ('58006', '/publish/forecast/AHA/yucheng.html', '虞城'),
       ('57088', '/publish/forecast/AHA/yuzhou.html', '禹州'),
       ('53989', '/publish/forecast/AHA/yuanyang.html', '原阳'),
       ('57175', '/publish/forecast/AHA/zhenping.html', '镇平'),
       ('57295', '/publish/forecast/AHA/zhengyang.html', '正阳'),
       ('57090', '/publish/forecast/AHA/zhongmu.html', '中牟'),
       ('57076', '/publish/forecast/AHA/yanshi.html', '偃师'),
       ('57180', '/publish/forecast/AHA/jiaxian.html', '郏县'),
       ('57095', '/publish/forecast/AHA/yanling.html', '鄢陵'),
       ('57081', '/publish/forecast/AHA/xingyang.html', '荥阳'),
       ('57162', '/publish/forecast/AHA/songxian.html', '嵩县'),
       ('53974', '/publish/forecast/AHA/qixian.html', '淇县'),
       ('57261', '/publish/forecast/AHA/xichuan.html', '淅川'),
       ('57063', '/publish/forecast/AHA/mianchi.html', '渑池'),
       ('57096', '/publish/forecast/AHA/qi-xian.html', '杞县'),
       ('58007', '/publish/forecast/AHA/zhecheng.html', '柘城'),
       ('57077', '/publish/forecast/AHA/luanchuan.html', '栾川'),
       ('58001', '/publish/forecast/AHA/hui-xian.html', '睢县');

update weather_city
set province = '河南省';

insert into alert_type (name)
values ('台风'),
       ('暴雨'),
       ('暴雪'),
       ('寒潮'),
       ('大风'),
       ('沙尘暴'),
       ('高温'),
       ('干旱'),
       ('雷电'),
       ('冰雹'),
       ('霜冻'),
       ('大雾'),
       ('道路结冰');